env:
  global:
    - secure: WZyCWhoIGMF6PO7alcLjqtOzBc3iaxwg4JhiVUhkldyXOiHFNSWec2IcetMPyKb9Yt2IEbonSzifjgxUUhHg0jr3Z4av4MH7QOGe8nMmjPe69DQrWw3ErhsV0UsBaOThzECo53whUEV1snK/niYeFYV45lIiVkBn01xp08AHqaE=
language: rust
rust:
  - nightly
after_script:
  - cargo doc --no-deps
  - mv target/doc doc
  - cd curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh
